<?php return 
array (
  'web_title' => '跳蛙二手交易平台',
  'tell' => '010-85864556',
  'e-mail' => '954693561@qq.com',
  'description' => '买买买卖卖卖',
  'web_status' => NULL,
  'recordnumber' => '312141',
  'dcsa' => NULL,
  'cdsc' => NULL,
  '' => NULL,
  'dqx' => NULL,
  'ds' => NULL,
  3 => NULL,
  'qqqqqqq' => NULL,
  'ddd' => NULL,
  'sss' => NULL,
  'rtrt' => NULL,
  'sad' => NULL,
  '的味道' => NULL,
  '发的我' => NULL,
);